// ─────────────────────────────────────────────────────────────────────────────
// exportUtils.js — Convert a message array to JSON, Markdown, or PDF
// All functions are pure: input messages[], output string or trigger download.
// ─────────────────────────────────────────────────────────────────────────────

const PROVIDER_LABELS = {
  claude: 'Claude', chatgpt: 'ChatGPT', gemini: 'Gemini', grok: 'Grok',
};

function formatTimestamp(iso) {
  return new Date(iso).toLocaleString([], {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

function safeFilename(roomName) {
  return (roomName || 'transcript')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 48);
}

function triggerDownload(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ── JSON ─────────────────────────────────────────────────────────────────────

export function exportJSON(messages, roomName) {
  const data = {
    version: 1,
    exported_at: new Date().toISOString(),
    room_name: roomName || '',
    message_count: messages.length,
    messages: messages.map(m => ({
      id: m.id,
      sender: m.sender_name,
      content: m.content,
      is_ai: m.ai_model !== null,
      ai_model: m.ai_model || null,
      timestamp: m.created_at,
    })),
  };
  const json = JSON.stringify(data, null, 2);
  triggerDownload(json, `${safeFilename(roomName)}.json`, 'application/json');
}

// ── Markdown ──────────────────────────────────────────────────────────────────

export function exportMarkdown(messages, roomName) {
  const lines = [];
  const title = roomName || 'Transcript';
  const exportedAt = formatTimestamp(new Date().toISOString());

  lines.push(`# ${title}`);
  lines.push('');
  lines.push(`*Exported ${exportedAt} · ${messages.length} messages*`);
  lines.push('');
  lines.push('---');
  lines.push('');

  let lastDate = null;

  for (const m of messages) {
    const msgDate = new Date(m.created_at).toLocaleDateString([], {
      weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
    });

    if (msgDate !== lastDate) {
      if (lastDate !== null) lines.push('');
      lines.push(`### ${msgDate}`);
      lines.push('');
      lastDate = msgDate;
    }

    const time = new Date(m.created_at).toLocaleTimeString([], {
      hour: '2-digit', minute: '2-digit',
    });

    const sender = m.ai_model !== null
      ? `**${m.sender_name}** *(AI)*`
      : `**${m.sender_name}**`;

    lines.push(`${sender} · *${time}*`);
    lines.push('');

    // Indent message content, handle multi-line
    const contentLines = m.content.split('\n');
    for (const cl of contentLines) {
      lines.push(`> ${cl}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(`*Generated by BorgMeeting*`);

  const md = lines.join('\n');
  triggerDownload(md, `${safeFilename(roomName)}.md`, 'text/markdown');
}

// ── PDF (via browser print) ───────────────────────────────────────────────────

export function exportPDF(messages, roomName, skin) {
  const title = roomName || 'Transcript';
  const exportedAt = formatTimestamp(new Date().toISOString());

  // Build skin-aware color palette — fall back to neutral if skin unavailable
  const palette = getPalette(skin?.id);

  const messageRows = messages.map(m => {
    const time = new Date(m.created_at).toLocaleTimeString([], {
      hour: '2-digit', minute: '2-digit',
    });
    const date = new Date(m.created_at).toLocaleDateString([], {
      month: 'short', day: 'numeric',
    });
    const isAI = m.ai_model !== null;
    const content = escapeHtml(m.content).replace(/\n/g, '<br>');

    return `
      <div class="msg ${isAI ? 'msg-ai' : 'msg-human'}">
        <div class="msg-meta">
          <span class="msg-sender">${escapeHtml(m.sender_name)}${isAI ? ' <span class="ai-tag">AI</span>' : ''}</span>
          <span class="msg-time">${date} ${time}</span>
        </div>
        <div class="msg-content">${content}</div>
      </div>`;
  }).join('\n');

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${escapeHtml(title)}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400&display=swap');

  * { box-sizing: border-box; margin: 0; padding: 0; }

  body {
    font-family: 'Inter', system-ui, sans-serif;
    font-size: 13px;
    line-height: 1.6;
    color: ${palette.text};
    background: #fff;
    padding: 48px 56px;
    max-width: 720px;
    margin: 0 auto;
  }

  .header {
    border-bottom: 2px solid ${palette.accent};
    padding-bottom: 20px;
    margin-bottom: 32px;
  }

  .header-title {
    font-size: 22px;
    font-weight: 600;
    color: ${palette.heading};
    letter-spacing: -0.3px;
    margin-bottom: 4px;
  }

  .header-meta {
    font-size: 11px;
    color: ${palette.muted};
    letter-spacing: 0.02em;
  }

  .header-accent {
    display: inline-block;
    width: 32px;
    height: 3px;
    background: ${palette.accent};
    border-radius: 2px;
    margin-bottom: 12px;
  }

  .msg {
    margin-bottom: 18px;
    padding: 12px 16px;
    border-radius: 8px;
    page-break-inside: avoid;
  }

  .msg-human {
    background: ${palette.humanBg};
    border-left: 3px solid ${palette.humanBorder};
  }

  .msg-ai {
    background: ${palette.aiBg};
    border-left: 3px solid ${palette.aiAccent};
  }

  .msg-meta {
    display: flex;
    align-items: baseline;
    gap: 10px;
    margin-bottom: 6px;
  }

  .msg-sender {
    font-weight: 600;
    font-size: 12px;
    color: ${palette.heading};
    letter-spacing: 0.01em;
  }

  .msg-time {
    font-size: 10px;
    color: ${palette.muted};
    margin-left: auto;
  }

  .ai-tag {
    display: inline-block;
    font-size: 9px;
    font-weight: 600;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    background: ${palette.aiAccent};
    color: ${palette.aiTagText};
    padding: 1px 5px;
    border-radius: 3px;
    vertical-align: middle;
    margin-left: 4px;
    font-family: 'JetBrains Mono', monospace;
  }

  .msg-content {
    font-size: 13px;
    color: ${palette.text};
    white-space: pre-wrap;
    word-break: break-word;
  }

  .footer {
    margin-top: 40px;
    padding-top: 16px;
    border-top: 1px solid ${palette.border};
    font-size: 10px;
    color: ${palette.muted};
    display: flex;
    justify-content: space-between;
  }

  @media print {
    body { padding: 24px 32px; }
    .msg { page-break-inside: avoid; }
  }
</style>
</head>
<body>
  <div class="header">
    <div class="header-accent"></div>
    <div class="header-title">${escapeHtml(title)}</div>
    <div class="header-meta">Exported ${exportedAt} · ${messages.length} messages</div>
  </div>

  <div class="messages">
    ${messageRows}
  </div>

  <div class="footer">
    <span>BorgMeeting transcript</span>
    <span>${escapeHtml(title)} · ${messages.length} messages</span>
  </div>
</body>
</html>`;

  const win = window.open('', '_blank', 'width=800,height=900');
  if (!win) {
    alert('Please allow popups to export PDF.');
    return;
  }
  win.document.write(html);
  win.document.close();
  win.onload = () => {
    setTimeout(() => {
      win.focus();
      win.print();
      // win.close(); — commented out: let user close after saving
    }, 400);
  };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function escapeHtml(str) {
  return (str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function getPalette(skinId) {
  const palettes = {
    borg: {
      text: '#1a1a18', heading: '#0a0a08', muted: '#888880',
      accent: '#00cc33', border: '#d0d0c8',
      humanBg: '#f8f8f4', humanBorder: '#d0d0c8',
      aiBg: '#f0fff4', aiAccent: '#00cc33', aiTagText: '#fff',
    },
    therapy: {
      text: '#3d2b1f', heading: '#2a1a10', muted: '#b09080',
      accent: '#c27b5a', border: '#ecddd4',
      humanBg: '#fdf8f4', humanBorder: '#ecddd4',
      aiBg: '#fff8f4', aiAccent: '#c27b5a', aiTagText: '#fff',
    },
    launch: {
      text: '#1a1b3a', heading: '#0f1028', muted: '#8888aa',
      accent: '#4f46e5', border: '#d6d9ff',
      humanBg: '#f8f8ff', humanBorder: '#d6d9ff',
      aiBg: '#f0f0ff', aiAccent: '#4f46e5', aiTagText: '#fff',
    },
    vacation: {
      text: '#1a120a', heading: '#0f0a04', muted: '#b09060',
      accent: '#f59e0b', border: '#fddba8',
      humanBg: '#fffdf8', humanBorder: '#fddba8',
      aiBg: '#fffbf0', aiAccent: '#f59e0b', aiTagText: '#1a120a',
    },
    dark: {
      text: '#1a1a24', heading: '#0e0e18', muted: '#888898',
      accent: '#7c3aed', border: '#d4d4e8',
      humanBg: '#f8f8fc', humanBorder: '#d4d4e8',
      aiBg: '#f4f0ff', aiAccent: '#7c3aed', aiTagText: '#fff',
    },
  };
  return palettes[skinId] || palettes['launch'];
}